### ISSUE TITLE
How do you generate the security key?

### ISSUE THREAD

**Issue by richardthombs** [jonhilt/NetCoreAuth#1]
Where do you get this value from please?

https://github.com/jonhilt/NetCoreAuth/blob/master/NetCoreJWTAuth.App/appsettings.json#L2

**Comment by jonhilt** [comment]
Hey,

Can't quite remember but I'm pretty sure I just made that up. 

I believe the signing key is used by ASP.NET Core to simply verify that any tokens on incoming requests were issued by this application (originally signed using the signing key).

Worth noting that the JWT isn't actually encrypted so you can easily read it's contents without this secret, the secret is simply used to sign the token so that your app can then check it's a token that it issued (and not some random token generated by some other app that doesn't have the same signing key).

**Comment by karelkral** [comment]
As noted [here](https://www.blinkingcaret.com/2017/09/06/secure-web-api-in-asp-net-core/) secret can be any string at least 16 chars long.
```
var secretKey = new SymmetricSecurityKey(Endoding.UTF8.GetBytes("a secret that needs to be at least 16 characters long"));
```

**Comment by richardthombs** [comment]
Thank you both!
